version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  forecast-alert-db:
    image: postgres:latest
    container_name: forecast-alert-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeitdb
      POSTGRES_DB: forecast_alerts
    volumes:
      - ./api/data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - my-network

  forecast-alert-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: forecast-alert-api
    environment:
      DATABASE_URL: "Host=forecast-alert-db;Port=5432;Database=forecast_alerts;Username=postgres;Password=changeitdb"
    depends_on:
      - forecast-alert-db
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "forecast_alerts", "-h", "forecast-alert-db", "-p", "5432"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - my-network
    volumes:
    - ./api/certs:/app/certs
